FlightMVC/Controllers/DemosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FlightMVC.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using FlightMVC.Filters;
using System.Diagnostics;
using Microsoft.Extensions.Logging;
using System.IO;

namespace FlightMVC.Controllers
{
    [ServiceFilter(typeof(MyExceptionFilterAttribute))]
    [Route("theRoot")]
    public class DemosController : Controller
    {
        private ILogger _logger;
        public DemosController(ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger("**** <><><> Demo Controller Logger");
        }


        [HttpGet("UploadDemo")]
        public IActionResult UploadDemo()
        {
            return View();
        }


        [HttpPost("UploadDemo")]
        public async Task<IActionResult> UploadDemo(UploadFilesDTO dto)
        {
            var list = new List<string>();

            if (dto.File != null)
            {
                string filePath = Path.GetTempFileName();  // only 65000 temp files allowed ( UBound(short) )
                using (FileStream fs = new FileStream(filePath, FileMode.OpenOrCreate))
                {
                    await dto.File.CopyToAsync(fs);
                }
                list.Add(dto.File.FileName + " -> " + filePath);
            }

            if (dto.Files != null)
            {
                foreach (var item in dto.Files)
                {
                    if (item == null) continue;
                    string filePath = Path.GetTempFileName();  // only 65000 temp files allowed ( UBound(short) )
                    using (FileStream fs = new FileStream(filePath, FileMode.OpenOrCreate))
                    {
                        await item.CopyToAsync(fs);
                    }
                    list.Add(item.FileName + " -> " + filePath);
                }
            }

            if (list.Count == 0)
            {
                ModelState.AddModelError(string.Empty, "file needs selecting first mate.");
            }

            ViewBag.Results = list;

            return View();
        }

        [TypeFilter(typeof(MyActionFilterAttribute))]
        [HttpGet("Action")]
        public IActionResult ActionFilterDemo()
        {
            _logger.LogInformation("++++++++++++++++++++++++++++++++ In ActionDemo +++++++++++++++++++++++++++");
            return View();
        }


        [HttpGet("Powers")]
        public IActionResult Powers()
        {
            List<NumPowersVM> list = new List<NumPowersVM>();
            for (int i = 0; i < 10; i++)
            {
                list.Add(new NumPowersVM() { Num = i });
            }
            return View(list);
        }

        [HttpGet("Problem")]
        public IActionResult Problem()
        {
            throw new ApplicationException();
        }


        [Route("selectdemo")]
        public IActionResult SelectDemo()
        {
            List<SelectListItem> list = new List<SelectListItem>();
            list.Add(new SelectListItem() { Text = "one", Value = "1", Selected = false });
            list.Add(new SelectListItem() { Text = "two", Value = "2", Selected = false });
            list.Add(new SelectListItem() { Text = "three", Value = "3", Selected = true });
            ViewData["Items"] = list;
            return View();
        }

        [Route("~/noroot/index")]
        public IActionResult NewIndex()
        {
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet("~/tyeth/square/{val:int}/{str?}")]
        public IActionResult Square(int val, string str = "")
        {
            return new ContentResult() { Content = (val * val) + str.ToString() };
        }

        [HttpGet("square/{val:int}")]
        public IActionResult Square(int val)
        {
            return new ContentResult() { Content = (val * val).ToString() };
        }


        [HttpGet("square/{val:alpha}")]
        public IActionResult Square(string val)

        {
            int result = 0;
            switch (val)
            {
                case "two":
                    result = 4; break;

                case "three":
                    result = 9; break;

                case "four":
                    result = 16; break;

                default:
                    break;
            }
            return new ContentResult() { Content = (result).ToString() };
        }
    }
}

FlightMVC/Controllers/PassengersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using FlightMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FlightMVC.Controllers
{
    [Authorize(Roles="AdminOnly")]
    public class PassengersController : Controller
    {

        static List<PassengerDetails> _passengers = new List<PassengerDetails>();
        static PassengersController()
        {
            for (int i = 0; i < 10; i++)
            {
                _passengers.Add(new PassengerDetails
                {
                    Name = $"Fred{i}",
                    Weight = 10 + i,
                    Prefs = new Preferences { Food = "No restrictions", ExtraLegRoom =(i %2==0) ? true: false }
                });
            }
        }
        // GET: Passengers
        public ActionResult Index()
        {
            return View(_passengers);
        }

        // GET: Passengers/Details/5
        public ActionResult Details(string id)
        {
            return FindAndDisplay(id);
        }

        private ActionResult FindAndDisplay(string id)
        {
            var passenger = _passengers.FirstOrDefault(x => x.Name == id);
            if (passenger == null) return NotFound("passenger not found");
            return View(passenger);
        }

        // GET: Passengers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Passengers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Passengers/Edit/5
        public ActionResult Edit(string id)
        {

            return FindAndDisplay (id);
        }

        // POST: Passengers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, PassengerDetails collection)
        {                               // defaults to IFormCollection
            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add update logic here
                    var pd = _passengers.FirstOrDefault(p => p.Name == id);
                    if (pd == null) return NotFound();
                    //PutInSession(pd);
                    PassengerDetails pdOld = pd.Clone() as PassengerDetails;
                    pd.Weight = collection.Weight;

                    PutInSession(pdOld, pd);
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return FindAndDisplay(id);
                }
            }
            else {
                return View(collection); }
            }

        public IActionResult Changes()
        {
            var pdTuple = GetFromSession();
            if (pdTuple == null) return NotFound();
            return View(pdTuple);
        }

        private void PutInSession(PassengerDetails pdOld, PassengerDetails pdNew)
        {
            JsonSerializer js = new JsonSerializer();
            StringWriter sw = new StringWriter();
            js.Serialize(sw,new Tuple<PassengerDetails,PassengerDetails>( pdOld,pdNew));
            var jsonOutput = sw.ToString();
            HttpContext.Session.SetString("Change", jsonOutput);

//            HttpContext.Session.SetString("Change",Newtonsoft.Json.JsonConvert.SerializeObject(pd));
        }


        private Tuple<PassengerDetails,PassengerDetails> GetFromSession()
        {
            var jsonInput = HttpContext.Session.GetString("Change");
            //return Newtonsoft.Json.JsonConvert.DeserializeObject<PassengerDetails>(jsonInput);

            JsonSerializer js = new JsonSerializer();
            Tuple<PassengerDetails,PassengerDetails> pd = null ;
            if (!string.IsNullOrEmpty(jsonInput))
            {
                StringReader sw = new StringReader(jsonInput);
                pd = js.Deserialize(sw, typeof(Tuple<PassengerDetails, PassengerDetails>)) as Tuple<PassengerDetails, PassengerDetails>;
            }
            return pd;

        }


        // GET: Passengers/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Passengers/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

FlightMVC/Controllers/PassengersRepController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using FlightMVC.Models;
using FlightMVC.Repositories;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;

namespace FlightMVC.Controllers
{
    public class PassengersRepController : Controller
    {
        IPassengersRepository _passengers = null;
        ConfigData configData = null;

        public PassengersRepController(IPassengersRepository repo,IOptions<ConfigData> data)

        {
            configData = data.Value;
            _passengers = repo;
        }
        
        // GET: Passengers
        public ActionResult Index()
        {
            return View("/Views/Passengers/Index.cshtml",_passengers.GetPassengers());
        }

        // GET: Passengers/Details/5
        public ActionResult Details(string id,[FromServices]ILoggerFactory factory)
        {
            factory.CreateLogger("log2").LogInformation($"Details for ({configData.Item1}) {id} <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<");
            return FindAndDisplay(id);
        }

        private ActionResult FindAndDisplay(string id)
        {
            var passenger = _passengers.GetPassengers().FirstOrDefault(x => x.Name == id);
            if (passenger == null) return NotFound("passenger not found");
            return View("/Views/Passengers/Details.cshtml", passenger);
        }

        // GET: Passengers/Create
        public ActionResult Create()
        {
            return View("/Views/Passengers/Create.cshtml");
        }

        // POST: Passengers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

//        // GET: Passengers/Edit/5
//        public ActionResult Edit(string id)
//        {

//            return FindAndDisplay (id);
//        }

//        // POST: Passengers/Edit/5
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public ActionResult Edit(string id, PassengerDetails collection)
//        {                               // defaults to IFormCollection
//            if (ModelState.IsValid)
//            {


//                try
//                {
//                    // TODO: Add update logic here
//                    var pd = _passengers.FirstOrDefault(p => p.Name == id);
//                    if (pd == null) return NotFound();
//                    //PutInSession(pd);
//                    PassengerDetails pdOld = pd.Clone() as PassengerDetails;
//                    pd.Weight = collection.Weight;

//                    PutInSession(pdOld, pd);
//                    return RedirectToAction(nameof(Index));
//                }
//                catch
//                {
//                    return FindAndDisplay(id);
//                }
//            }
//            else { return View(collection); }
//            }

//        public IActionResult Changes()
//        {
//            var pdTuple = GetFromSession();
//            if (pdTuple == null) return NotFound();
//            return View(pdTuple);
//        }

//        private void PutInSession(PassengerDetails pdOld, PassengerDetails pdNew)
//        {
//            JsonSerializer js = new JsonSerializer();
//            StringWriter sw = new StringWriter();
//            js.Serialize(sw,new Tuple<PassengerDetails,PassengerDetails>( pdOld,pdNew));
//            var jsonOutput = sw.ToString();
//            HttpContext.Session.SetString("Change", jsonOutput);

////            HttpContext.Session.SetString("Change",Newtonsoft.Json.JsonConvert.SerializeObject(pd));
//        }


//        private Tuple<PassengerDetails,PassengerDetails> GetFromSession()
//        {
//            var jsonInput = HttpContext.Session.GetString("Change");
//            //return Newtonsoft.Json.JsonConvert.DeserializeObject<PassengerDetails>(jsonInput);

//            JsonSerializer js = new JsonSerializer();
//            Tuple<PassengerDetails,PassengerDetails> pd = null ;
//            if (!string.IsNullOrEmpty(jsonInput))
//            {
//                StringReader sw = new StringReader(jsonInput);
//                pd = js.Deserialize(sw, typeof(Tuple<PassengerDetails, PassengerDetails>)) as Tuple<PassengerDetails, PassengerDetails>;
//            }
//            return pd;

//        }


//        // GET: Passengers/Delete/5
//        public ActionResult Delete(int id)
//        {
//            return View();
//        }

//        // POST: Passengers/Delete/5
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public ActionResult Delete(int id, IFormCollection collection)
//        {
//            try
//            {
//                // TODO: Add delete logic here

//                return RedirectToAction(nameof(Index));
//            }
//            catch
//            {
//                return View();
//            }
//        }
    }
}

FlightMVC/Views/Shared/Preferences.cshtml
@model FlightMVC.Models.Preferences

<div>
    <h4>Preferences Partial</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label asp-for="Food"></label>
        </dt>
        <dd>
            <p asp-for="Food"></p>
        </dd>
        <dt>
            <label asp-for="ExtraLegRoom"></label>
        </dt>
        <dd>
            <input type="checkbox" asp-for="ExtraLegRoom" />
            <p asp-for="ExtraLegRoom"></p>
        </dd>
    </dl>
</div>

FlightMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlightMVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FlightMVC</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Demos" asp-action="Powers">Powers</a></li>
                    <li><a asp-area="" asp-controller="Demos" asp-action="ActionFilterDemo">Action</a></li>

                    <li><a asp-area="" asp-controller="Demos" asp-action="UploadDemo">Upload</a></li>
                    <li><a asp-area="FlightInfo" asp-controller="Flights" asp-action="Index">Flights</a></li>
                    <li><a asp-area="" asp-controller="Passengers" asp-action="Index">PassengersRep</a></li>
                    <li><a asp-area="" asp-controller="PassengersRep" asp-action="Index">Passengers</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - FlightMVC</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>